In [1]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import pandas as pd
import numpy as np
import os

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
# ==========================================================
# Load Cleaned Data
# ==========================================================

sales_df = pd.read_csv("../data/processed/clean_sales.csv")
calendar_df = pd.read_csv("../data/processed/clean_calendar.csv")
prices_df = pd.read_csv("../data/processed/clean_prices.csv")

print("Datasets loaded successfully!")

Datasets loaded successfully!

In [3]:
calendar_df["date"] = pd.to_datetime(calendar_df["date"])

In [4]:
# ==========================================================
# Time Features
# ==========================================================

calendar_df["day"] = calendar_df["date"].dt.day
calendar_df["month_name"] = calendar_df["date"].dt.month_name()
calendar_df["quarter"] = calendar_df["date"].dt.quarter
calendar_df["week"] = calendar_df["date"].dt.isocalendar().week.astype(int)

print("Time features created successfully!")

Time features created successfully!

In [5]:
calendar_df[
    [
        "date",
        "year",
        "month",
        "month_name",
        "day",
        "week",
        "quarter",
    ]
].head()

        date  year  month month_name  day  week  quarter
0 2011-01-29  2011      1    January   29     4        1
1 2011-01-30  2011      1    January   30     4        1
2 2011-01-31  2011      1    January   31     5        1
3 2011-02-01  2011      2   February    1     5        1
4 2011-02-02  2011      2   February    2     5        1

In [6]:
# ==========================================================
# Weekend Indicator
# ==========================================================

calendar_df["is_weekend"] = calendar_df["weekday"].isin(["Saturday", "Sunday"]).astype(int)

print("Weekend feature created successfully!")

Weekend feature created successfully!

In [7]:
calendar_df[["weekday", "wday", "is_weekend"]].head(10)

     weekday  wday  is_weekend
0   Saturday     1           1
1     Sunday     2           1
2     Monday     3           0
3    Tuesday     4           0
4  Wednesday     5           0
5   Thursday     6           0
6     Friday     7           0
7   Saturday     1           1
8     Sunday     2           1
9     Monday     3           0

In [8]:
# ==========================================================
# Event Indicator
# ==========================================================

calendar_df["has_event"] = (
    (calendar_df["event_name_1"] != "No_Event") |
    (calendar_df["event_name_2"] != "No_Event")
).astype(int)

print("Event indicator created successfully!")

Event indicator created successfully!

In [9]:
calendar_df[
    [
        "date",
        "event_name_1",
        "event_name_2",
        "has_event"
    ]
].head(15)

         date event_name_1 event_name_2  has_event
0  2011-01-29     No_Event     No_Event          0
1  2011-01-30     No_Event     No_Event          0
2  2011-01-31     No_Event     No_Event          0
3  2011-02-01     No_Event     No_Event          0
4  2011-02-02     No_Event     No_Event          0
5  2011-02-03     No_Event     No_Event          0
6  2011-02-04     No_Event     No_Event          0
7  2011-02-05     No_Event     No_Event          0
8  2011-02-06    SuperBowl     No_Event          1
9  2011-02-07     No_Event     No_Event          0
10 2011-02-08     No_Event     No_Event          0
11 2011-02-09     No_Event     No_Event          0
12 2011-02-10     No_Event     No_Event          0
13 2011-02-11     No_Event     No_Event          0
14 2011-02-12     No_Event     No_Event          0

In [10]:
print("Total Event Days     :", calendar_df["has_event"].sum())
print("Total Non-Event Days :", len(calendar_df) - calendar_df["has_event"].sum())

Total Event Days     : 162
Total Non-Event Days : 1807

In [11]:
# ==========================================================
# Event Indicator
# ==========================================================

calendar_df["has_event"] = (
    (calendar_df["event_name_1"] != "No_Event") |
    (calendar_df["event_name_2"] != "No_Event")
).astype(int)

print("Event indicator created successfully!")

Event indicator created successfully!

In [12]:
calendar_df[
    [
        "date",
        "event_name_1",
        "event_name_2",
        "has_event"
    ]
].head(15)

         date event_name_1 event_name_2  has_event
0  2011-01-29     No_Event     No_Event          0
1  2011-01-30     No_Event     No_Event          0
2  2011-01-31     No_Event     No_Event          0
3  2011-02-01     No_Event     No_Event          0
4  2011-02-02     No_Event     No_Event          0
5  2011-02-03     No_Event     No_Event          0
6  2011-02-04     No_Event     No_Event          0
7  2011-02-05     No_Event     No_Event          0
8  2011-02-06    SuperBowl     No_Event          1
9  2011-02-07     No_Event     No_Event          0
10 2011-02-08     No_Event     No_Event          0
11 2011-02-09     No_Event     No_Event          0
12 2011-02-10     No_Event     No_Event          0
13 2011-02-11     No_Event     No_Event          0
14 2011-02-12     No_Event     No_Event          0

In [13]:
print("Total Event Days     :", calendar_df["has_event"].sum())
print("Total Non-Event Days :", len(calendar_df) - calendar_df["has_event"].sum())

Total Event Days     : 162
Total Non-Event Days : 1807

In [14]:
# ==========================================================
# SNAP Indicator
# ==========================================================

calendar_df["snap_active"] = (
    (calendar_df["snap_CA"] == 1) |
    (calendar_df["snap_TX"] == 1) |
    (calendar_df["snap_WI"] == 1)
).astype(int)

print("SNAP feature created successfully!")

SNAP feature created successfully!

In [15]:
calendar_df[
    [
        "date",
        "snap_CA",
        "snap_TX",
        "snap_WI",
        "snap_active"
    ]
].head(15)

         date  snap_CA  snap_TX  snap_WI  snap_active
0  2011-01-29        0        0        0            0
1  2011-01-30        0        0        0            0
2  2011-01-31        0        0        0            0
3  2011-02-01        1        1        0            1
4  2011-02-02        1        0        1            1
5  2011-02-03        1        1        1            1
6  2011-02-04        1        0        0            1
7  2011-02-05        1        1        1            1
8  2011-02-06        1        1        1            1
9  2011-02-07        1        1        0            1
10 2011-02-08        1        0        1            1
11 2011-02-09        1        1        1            1
12 2011-02-10        1        0        0            1
13 2011-02-11        0        1        1            1
14 2011-02-12        0        1        1            1

In [16]:
print("SNAP Active Days :", calendar_df["snap_active"].sum())
print("Non SNAP Days    :", len(calendar_df) - calendar_df["snap_active"].sum())

SNAP Active Days : 975
Non SNAP Days    : 994

In [17]:
feature_path = "../data/features"

os.makedirs(feature_path, exist_ok=True)

print("Feature folder is ready!")

Feature folder is ready!

In [18]:
calendar_df.to_csv("../data/features/calendar_features.csv", index=False)
sales_df.to_csv("../data/features/sales_features.csv", index=False)
prices_df.to_csv("../data/features/prices_features.csv", index=False)

print("Feature Engineering Completed Successfully!")

Feature Engineering Completed Successfully!

In [19]:
import os

print(os.listdir("../data/features"))

['calendar_features.csv', 'prices_features.csv', 'sales_features.csv']